### ISSUE TITLE
Automatic yumdb -> swdb transformation

### ISSUE THREAD

**Issue by MichaelMraka** [edynox/dnf#2]
When (any) command is going to open swdb and it isn't there, it would be nice if it can try migrate old yumdb to swdb.

**Comment by MichaelMraka** [comment]
Alternatively migration could be done in the %posttrans of dnf.rpm package.
But this is more tricky because there will be a running dnf transaction at the moment (the one which install new dnf version with swdb feature). Not sure if it can work this way...

**Comment by edcuba** [comment]
I think we can handle this in SwdbInterface(yum/history.py). Also it may be a good idea to move swdb_transformer form libhif to dnf, so there will be no need to look for it. On the other hand, when someone will make some change to hif-swdb in libhif, he will have to commit new transformer into dnf...

**Comment by edcuba** [comment]
autotransform functionality added
