### ISSUE TITLE
Fix unit tests

### ISSUE THREAD

**Issue by MichaelMraka** [edynox/dnf#3]
There are automatic tests runing during rpm package build. Now they fail because they expect old yumdb implementation.

```
1: Test command: /usr/bin/nosetests-2.7 "-s" "dnf-git-0.c533d7e/tests"
1: Test timeout computed to be: 9.99988e+06
1: EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
1: ======================================================================
1: ERROR: Failure: AttributeError ('module' object has no attribute 'YumHistory')
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "/usr/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
1:     addr.filename, addr.module)
1:   File "/usr/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
1:     return self.importFromDir(dir_path, fqname)
1:   File "/usr/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
1:     mod = load_module(part_fqname, fh, filename, desc)
1:   File "/tmp/tito/rpmbuild-dnff69smssx/BUILD/dnf-git-0.c533d7e/tests/automatic/test_emitter.py", line 20, in <module>
1:     from tests.support import mock, mock_open
1:   File "/tmp/tito/rpmbuild-dnff69smssx/BUILD/dnf-git-0.c533d7e/tests/support.py", line 298, in <module>
1:     class HistoryStub(dnf.yum.history.YumHistory):
1: AttributeError: 'module' object has no attribute 'YumHistory'
```

Also be aware running tests in python3:
/usr/bin/nosetests-3.5 "-s" "dnf-git-0.c533d7e/tests"

**Comment by edcuba** [comment]
@MichaelMraka 
This will be little more problematic. Like I mentioned, DNF is still using some own package object, which was held by old yumdb(like python object), not by history. Objects are retrieved by functions like
`"pkg, = base.sack.query().installed().filter(name='pepper')"`
and their atributes are set by
`"base._yumdb.get_package(pkg).get = {'reason': 'dep', 'from_repo': 'main'}.get"`
We can replace setting of atributes by

```
base.history.mark_user_installed(pkg, False)
base.history.set_repo(pkg, "main")
```

but package may not be in database yet, so actualy we can't...
It would be fine to unify package objects in dnf, so pkg will be already returned like HifSwdbPkg, which is easy to operate within swdb.

**Comment by edcuba** [comment]
@MichaelMraka 
unit tests should be fine now
